version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kpi_management
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: Node
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: kpi_management
    # command: sh -c "npm run db:migrate && npm run seed && npm start"
    command: sh -c "npm run db:migrate:docker && npm run start:docker"

  frontend:
    build: ./frontend
    container_name: Angular
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
