version: "3.9"
services:
  db:
    image: postgres:15
    container_name: kpi_management
    environment:
      POSTGRES_DB: kpi_management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d kpi_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: password
      DB_NAME: kpi_management
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
